# Generated by Django 4.0.4 on 2022-05-12 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedmodel')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=255, null=True, verbose_name='CPF/CNPJ')),
                ('status_atraso_pagamento', models.BooleanField(default=False)),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
            ],
            bases=('core.timestampedmodel',),
        ),
    ]
