# Generated by Django 4.0.4 on 2022-07-10 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedmodel')),
                ('codigo', models.CharField(max_length=255, verbose_name='Equipamento')),
                ('locacao_anterior', models.DateField(blank=True, null=True)),
                ('modelo', models.CharField(blank=True, max_length=255, null=True)),
                ('data_compra', models.DateField(blank=True, null=True)),
            ],
            bases=('core.timestampedmodel',),
        ),
    ]
