# Generated by Django 4.0.4 on 2022-07-18 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('equipamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedmodel')),
                ('facricacao', models.CharField(blank=True, max_length=255, null=True)),
                ('marca', models.CharField(max_length=255)),
                ('estado_conservacao', models.CharField(choices=[('1', 'Ruim'), ('2', 'Bom'), ('3', 'Ótimo')], max_length=255)),
            ],
            bases=('core.timestampedmodel',),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='codigo',
            field=models.CharField(max_length=255, verbose_name='Código'),
        ),
    ]
